apiVersion: v2
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x
description: EODAG (Earth Observation Data Access Gateway) is a tool for searching, aggregating results and downloading remote sensed images offering a unified API for data access regardless of the data provider.
name: eodag
version: 1.0.0
appVersion: 2.9.0
