extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

  # Collect own metrics
  prometheus:
    config:
      scrape_configs:
      - job_name: 'otel-collector'
        scrape_interval: 10s
        static_configs:
        - targets: ['0.0.0.0:8888']

processors:
  batch:

exporters:
  debug:
    verbosity: detailed
  # Data sources: metrics
  prometheus:
    endpoint: 0.0.0.0:8000
    namespace: eodag-otelcol-exporter

service:

  pipelines:

    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]

    metrics:
#      receivers: [otlp, prometheus]
      receivers: [otlp]
      processors: [batch]
      exporters: [debug,prometheus]

  extensions: [health_check, pprof, zpages]
