S1_OCN:
  desc: ""
  meta: []

S1_GRD:
  desc: ""
  meta: []

S1_SLC:
  desc: ""
  meta: []

S1_RAW:
  desc: ""
  meta: []

S3_SRA:
  desc: ""
  meta: []

S3_LAN:
  desc: ""
  meta: []

S3_SRA_BS:
  desc: ""
  meta: []

S3_SRA_A_BS:
  desc: ""
  meta: []

S2_MSI_L1C:
  desc: Sentinel 2
  meta:
    - key: PRODUCT_START_TIME
      type: date
    - key: PRODUCT_STOP_TIME
      type: date