# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eodag.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='eodag.proto',
  package='eodag',
  syntax='proto3',
  serialized_pb=_b('\n\x0b\x65odag.proto\x12\x05\x65odag\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/protobuf/any.proto\"\xa5\x02\n\x13\x45OProductTypeSchema\x12\n\n\x02id\x18\x01 \x01(\t\x12\x44\n\x04meta\x18\x02 \x03(\x0b\x32\x36.eodag.EOProductTypeSchema.EOProductTypeMetadataSchema\x1al\n\x1b\x45OProductTypeMetadataSchema\x12\x0b\n\x03key\x18\x01 \x01(\t\x12@\n\nvalue_type\x18\x02 \x01(\x0e\x32,.eodag.EOProductTypeSchema.MetadataValueType\"N\n\x11MetadataValueType\x12\x08\n\x04\x44\x41TE\x10\x00\x12\n\n\x06STRING\x10\x01\x12\t\n\x05\x46LOAT\x10\x02\x12\x0b\n\x07INTEGER\x10\x03\x12\x0b\n\x07POLYGON\x10\x04\"+\n\x1a\x45OProductTypeSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\"\xae\x01\n\x16\x45OProductSearchRequest\x12\x14\n\x0cproduct_type\x18\x01 \x01(\t\x12\x11\n\tfootprint\x18\x02 \x01(\t\x12)\n\x05start\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\'\n\x03\x65nd\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x17\n\x0fmetadata_filter\x18\x05 \x01(\t\"^\n\tEOProduct\x12\n\n\x02id\x18\x01 \x01(\t\x1a\x45\n\x11\x45OProductMetadata\x12\x0b\n\x03key\x18\x01 \x01(\t\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any\".\n\x18\x45OProductDownloadRequest\x12\x12\n\nproduct_id\x18\x02 \x01(\t\"\x1f\n\x0cNetCDFBuffer\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\x32\xba\x01\n\x14\x45OProductTypeService\x12J\n\x10ListProductTypes\x12\x16.google.protobuf.Empty\x1a\x1a.eodag.EOProductTypeSchema\"\x00\x30\x01\x12V\n\x11SearchProductType\x12!.eodag.EOProductTypeSearchRequest\x1a\x1a.eodag.EOProductTypeSchema\"\x00\x30\x01\x32\xa5\x01\n\x10\x45OProductService\x12\x44\n\rSearchProduct\x12\x1d.eodag.EOProductSearchRequest\x1a\x10.eodag.EOProduct\"\x00\x30\x01\x12K\n\x0f\x44ownloadProduct\x12\x1f.eodag.EOProductDownloadRequest\x1a\x13.eodag.NetCDFBuffer\"\x00\x30\x01\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])



_EOPRODUCTTYPESCHEMA_METADATAVALUETYPE = _descriptor.EnumDescriptor(
  name='MetadataValueType',
  full_name='eodag.EOProductTypeSchema.MetadataValueType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DATE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STRING', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FLOAT', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INTEGER', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POLYGON', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=327,
  serialized_end=405,
)
_sym_db.RegisterEnumDescriptor(_EOPRODUCTTYPESCHEMA_METADATAVALUETYPE)


_EOPRODUCTTYPESCHEMA_EOPRODUCTTYPEMETADATASCHEMA = _descriptor.Descriptor(
  name='EOProductTypeMetadataSchema',
  full_name='eodag.EOProductTypeSchema.EOProductTypeMetadataSchema',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='eodag.EOProductTypeSchema.EOProductTypeMetadataSchema.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value_type', full_name='eodag.EOProductTypeSchema.EOProductTypeMetadataSchema.value_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=325,
)

_EOPRODUCTTYPESCHEMA = _descriptor.Descriptor(
  name='EOProductTypeSchema',
  full_name='eodag.EOProductTypeSchema',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='eodag.EOProductTypeSchema.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='meta', full_name='eodag.EOProductTypeSchema.meta', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_EOPRODUCTTYPESCHEMA_EOPRODUCTTYPEMETADATASCHEMA, ],
  enum_types=[
    _EOPRODUCTTYPESCHEMA_METADATAVALUETYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=405,
)


_EOPRODUCTTYPESEARCHREQUEST = _descriptor.Descriptor(
  name='EOProductTypeSearchRequest',
  full_name='eodag.EOProductTypeSearchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='query', full_name='eodag.EOProductTypeSearchRequest.query', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=407,
  serialized_end=450,
)


_EOPRODUCTSEARCHREQUEST = _descriptor.Descriptor(
  name='EOProductSearchRequest',
  full_name='eodag.EOProductSearchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='product_type', full_name='eodag.EOProductSearchRequest.product_type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='footprint', full_name='eodag.EOProductSearchRequest.footprint', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start', full_name='eodag.EOProductSearchRequest.start', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end', full_name='eodag.EOProductSearchRequest.end', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='metadata_filter', full_name='eodag.EOProductSearchRequest.metadata_filter', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=453,
  serialized_end=627,
)


_EOPRODUCT_EOPRODUCTMETADATA = _descriptor.Descriptor(
  name='EOProductMetadata',
  full_name='eodag.EOProduct.EOProductMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='eodag.EOProduct.EOProductMetadata.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='eodag.EOProduct.EOProductMetadata.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=654,
  serialized_end=723,
)

_EOPRODUCT = _descriptor.Descriptor(
  name='EOProduct',
  full_name='eodag.EOProduct',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='eodag.EOProduct.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_EOPRODUCT_EOPRODUCTMETADATA, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=629,
  serialized_end=723,
)


_EOPRODUCTDOWNLOADREQUEST = _descriptor.Descriptor(
  name='EOProductDownloadRequest',
  full_name='eodag.EOProductDownloadRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='product_id', full_name='eodag.EOProductDownloadRequest.product_id', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=725,
  serialized_end=771,
)


_NETCDFBUFFER = _descriptor.Descriptor(
  name='NetCDFBuffer',
  full_name='eodag.NetCDFBuffer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='eodag.NetCDFBuffer.content', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=773,
  serialized_end=804,
)

_EOPRODUCTTYPESCHEMA_EOPRODUCTTYPEMETADATASCHEMA.fields_by_name['value_type'].enum_type = _EOPRODUCTTYPESCHEMA_METADATAVALUETYPE
_EOPRODUCTTYPESCHEMA_EOPRODUCTTYPEMETADATASCHEMA.containing_type = _EOPRODUCTTYPESCHEMA
_EOPRODUCTTYPESCHEMA.fields_by_name['meta'].message_type = _EOPRODUCTTYPESCHEMA_EOPRODUCTTYPEMETADATASCHEMA
_EOPRODUCTTYPESCHEMA_METADATAVALUETYPE.containing_type = _EOPRODUCTTYPESCHEMA
_EOPRODUCTSEARCHREQUEST.fields_by_name['start'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_EOPRODUCTSEARCHREQUEST.fields_by_name['end'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_EOPRODUCT_EOPRODUCTMETADATA.fields_by_name['value'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_EOPRODUCT_EOPRODUCTMETADATA.containing_type = _EOPRODUCT
DESCRIPTOR.message_types_by_name['EOProductTypeSchema'] = _EOPRODUCTTYPESCHEMA
DESCRIPTOR.message_types_by_name['EOProductTypeSearchRequest'] = _EOPRODUCTTYPESEARCHREQUEST
DESCRIPTOR.message_types_by_name['EOProductSearchRequest'] = _EOPRODUCTSEARCHREQUEST
DESCRIPTOR.message_types_by_name['EOProduct'] = _EOPRODUCT
DESCRIPTOR.message_types_by_name['EOProductDownloadRequest'] = _EOPRODUCTDOWNLOADREQUEST
DESCRIPTOR.message_types_by_name['NetCDFBuffer'] = _NETCDFBUFFER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EOProductTypeSchema = _reflection.GeneratedProtocolMessageType('EOProductTypeSchema', (_message.Message,), dict(

  EOProductTypeMetadataSchema = _reflection.GeneratedProtocolMessageType('EOProductTypeMetadataSchema', (_message.Message,), dict(
    DESCRIPTOR = _EOPRODUCTTYPESCHEMA_EOPRODUCTTYPEMETADATASCHEMA,
    __module__ = 'eodag_pb2'
    # @@protoc_insertion_point(class_scope:eodag.EOProductTypeSchema.EOProductTypeMetadataSchema)
    ))
  ,
  DESCRIPTOR = _EOPRODUCTTYPESCHEMA,
  __module__ = 'eodag_pb2'
  # @@protoc_insertion_point(class_scope:eodag.EOProductTypeSchema)
  ))
_sym_db.RegisterMessage(EOProductTypeSchema)
_sym_db.RegisterMessage(EOProductTypeSchema.EOProductTypeMetadataSchema)

EOProductTypeSearchRequest = _reflection.GeneratedProtocolMessageType('EOProductTypeSearchRequest', (_message.Message,), dict(
  DESCRIPTOR = _EOPRODUCTTYPESEARCHREQUEST,
  __module__ = 'eodag_pb2'
  # @@protoc_insertion_point(class_scope:eodag.EOProductTypeSearchRequest)
  ))
_sym_db.RegisterMessage(EOProductTypeSearchRequest)

EOProductSearchRequest = _reflection.GeneratedProtocolMessageType('EOProductSearchRequest', (_message.Message,), dict(
  DESCRIPTOR = _EOPRODUCTSEARCHREQUEST,
  __module__ = 'eodag_pb2'
  # @@protoc_insertion_point(class_scope:eodag.EOProductSearchRequest)
  ))
_sym_db.RegisterMessage(EOProductSearchRequest)

EOProduct = _reflection.GeneratedProtocolMessageType('EOProduct', (_message.Message,), dict(

  EOProductMetadata = _reflection.GeneratedProtocolMessageType('EOProductMetadata', (_message.Message,), dict(
    DESCRIPTOR = _EOPRODUCT_EOPRODUCTMETADATA,
    __module__ = 'eodag_pb2'
    # @@protoc_insertion_point(class_scope:eodag.EOProduct.EOProductMetadata)
    ))
  ,
  DESCRIPTOR = _EOPRODUCT,
  __module__ = 'eodag_pb2'
  # @@protoc_insertion_point(class_scope:eodag.EOProduct)
  ))
_sym_db.RegisterMessage(EOProduct)
_sym_db.RegisterMessage(EOProduct.EOProductMetadata)

EOProductDownloadRequest = _reflection.GeneratedProtocolMessageType('EOProductDownloadRequest', (_message.Message,), dict(
  DESCRIPTOR = _EOPRODUCTDOWNLOADREQUEST,
  __module__ = 'eodag_pb2'
  # @@protoc_insertion_point(class_scope:eodag.EOProductDownloadRequest)
  ))
_sym_db.RegisterMessage(EOProductDownloadRequest)

NetCDFBuffer = _reflection.GeneratedProtocolMessageType('NetCDFBuffer', (_message.Message,), dict(
  DESCRIPTOR = _NETCDFBUFFER,
  __module__ = 'eodag_pb2'
  # @@protoc_insertion_point(class_scope:eodag.NetCDFBuffer)
  ))
_sym_db.RegisterMessage(NetCDFBuffer)



_EOPRODUCTTYPESERVICE = _descriptor.ServiceDescriptor(
  name='EOProductTypeService',
  full_name='eodag.EOProductTypeService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=807,
  serialized_end=993,
  methods=[
  _descriptor.MethodDescriptor(
    name='ListProductTypes',
    full_name='eodag.EOProductTypeService.ListProductTypes',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_EOPRODUCTTYPESCHEMA,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SearchProductType',
    full_name='eodag.EOProductTypeService.SearchProductType',
    index=1,
    containing_service=None,
    input_type=_EOPRODUCTTYPESEARCHREQUEST,
    output_type=_EOPRODUCTTYPESCHEMA,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_EOPRODUCTTYPESERVICE)

DESCRIPTOR.services_by_name['EOProductTypeService'] = _EOPRODUCTTYPESERVICE


_EOPRODUCTSERVICE = _descriptor.ServiceDescriptor(
  name='EOProductService',
  full_name='eodag.EOProductService',
  file=DESCRIPTOR,
  index=1,
  options=None,
  serialized_start=996,
  serialized_end=1161,
  methods=[
  _descriptor.MethodDescriptor(
    name='SearchProduct',
    full_name='eodag.EOProductService.SearchProduct',
    index=0,
    containing_service=None,
    input_type=_EOPRODUCTSEARCHREQUEST,
    output_type=_EOPRODUCT,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DownloadProduct',
    full_name='eodag.EOProductService.DownloadProduct',
    index=1,
    containing_service=None,
    input_type=_EOPRODUCTDOWNLOADREQUEST,
    output_type=_NETCDFBUFFER,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_EOPRODUCTSERVICE)

DESCRIPTOR.services_by_name['EOProductService'] = _EOPRODUCTSERVICE

# @@protoc_insertion_point(module_scope)
