# -*- coding: utf-8 -*-
# Copyright 2018, CS GROUP - France, https://www.csgroup.eu/
#
# This file is part of EODAG project
#     https://www.github.com/CS-SI/EODAG
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
from eodag.utils import GENERIC_COLLECTION

SUPPORTED_COLLECTIONS = {
    "AERIS_IAGOS": ["dedl"],
    "AG_ERA5": ["cop_cds", "wekeo_ecmwf"],
    "CAMS_GAC_FORECAST": ["cop_ads", "dedl", "wekeo_ecmwf"],
    "CAMS_EU_AIR_QUALITY_FORECAST": ["cop_ads", "dedl", "wekeo_ecmwf"],
    "CAMS_GFE_GFAS": ["cop_ads", "dedl", "wekeo_ecmwf"],
    "CAMS_GRF": ["cop_ads", "dedl", "wekeo_ecmwf"],
    "CAMS_GRF_AUX": ["cop_ads", "dedl", "wekeo_ecmwf"],
    "CAMS_SOLAR_RADIATION": ["cop_ads", "dedl", "wekeo_ecmwf"],
    "CAMS_GREENHOUSE_EGG4_MONTHLY": ["cop_ads", "dedl", "wekeo_ecmwf"],
    "CAMS_GREENHOUSE_EGG4": ["cop_ads", "dedl", "wekeo_ecmwf"],
    "CAMS_GREENHOUSE_INVERSION": ["cop_ads", "dedl", "wekeo_ecmwf"],
    "CAMS_GLOBAL_EMISSIONS": ["cop_ads", "dedl", "wekeo_ecmwf"],
    "CAMS_EAC4": ["cop_ads", "dedl", "wekeo_ecmwf"],
    "CAMS_EAC4_MONTHLY": ["cop_ads", "dedl", "wekeo_ecmwf"],
    "CAMS_EU_AIR_QUALITY_RE": ["cop_ads", "dedl", "wekeo_ecmwf"],
    "CBERS4_AWFI_L2": ["aws_eos"],
    "CBERS4_AWFI_L4": ["aws_eos"],
    "CBERS4_MUX_L2": ["aws_eos"],
    "CBERS4_MUX_L4": ["aws_eos"],
    "CBERS4_PAN10M_L2": ["aws_eos"],
    "CBERS4_PAN10M_L4": ["aws_eos"],
    "CBERS4_PAN5M_L2": ["aws_eos"],
    "CBERS4_PAN5M_L4": ["aws_eos"],
    "CLMS_CORINE": ["dedl", "wekeo_main"],
    "CLMS_GLO_DMP_333M": ["dedl", "wekeo_main"],
    "CLMS_GLO_FAPAR_333M": ["dedl", "wekeo_main"],
    "CLMS_GLO_FCOVER_333M": ["dedl", "wekeo_main"],
    "CLMS_GLO_GDMP_333M": ["dedl", "wekeo_main"],
    "CLMS_GLO_LAI_333M": ["dedl", "wekeo_main"],
    "CLMS_GLO_NDVI_1KM_LTS": ["dedl", "wekeo_main"],
    "CLMS_GLO_NDVI_333M": ["dedl", "wekeo_main"],
    "CLMS_HRVPP_ST": ["wekeo_main"],
    "CLMS_HRVPP_ST_LAEA": ["wekeo_main"],
    "CLMS_HRVPP_VPP": ["wekeo_main"],
    "CLMS_HRVPP_VPP_LAEA": ["wekeo_main"],
    "COP_DEM_GLO30_DGED": [
        "creodias",
        "creodias_s3",
        "dedl",
        "earth_search",
        "wekeo_main",
    ],
    "COP_DEM_GLO30_DTED": ["creodias", "creodias_s3", "dedl", "wekeo_main"],
    "COP_DEM_GLO90_DGED": [
        "creodias",
        "creodias_s3",
        "dedl",
        "earth_search",
        "wekeo_main",
    ],
    "COP_DEM_GLO90_DTED": ["creodias", "creodias_s3", "dedl", "wekeo_main"],
    "DT_CLIMATE_ADAPTATION": ["dedl", "dedt_lumi"],
    "DT_EXTREMES": ["dedl", "dedt_lumi"],
    "DT_CLIMATE_G1_HIGHRESMIP_CONT_IFS_FESOM_R1": ["dedt_mn5"],
    "DT_CLIMATE_G1_SCENARIOMIP_SSP3_7_0_IFS_FESOM_R1": ["dedt_mn5"],
    "DT_CLIMATE_G1_CMIP6_HIST_ICON_R1": ["dedt_lumi"],
    "DT_CLIMATE_G1_CMIP6_HIST_IFS_NEMO_R1": ["dedt_lumi"],
    "DT_CLIMATE_G1_HIGHRESMIP_CONT_IFS_NEMO_R1": ["dedt_lumi"],
    "DT_CLIMATE_G1_SCENARIOMIP_SSP3_7_0_ICON_R1": ["dedt_lumi"],
    "DT_CLIMATE_G1_SCENARIOMIP_SSP3_7_0_IFS_NEMO_R1": ["dedt_lumi"],
    "DT_CLIMATE_G1_STORY_NUDGING_CONT_IFS_FESOM_R1": ["dedt_lumi"],
    "DT_CLIMATE_G1_STORY_NUDGING_HIST_IFS_FESOM_R1": ["dedt_lumi"],
    "DT_CLIMATE_G1_STORY_NUDGING_TPLUS2_0K_IFS_FESOM_R1": ["dedt_lumi"],
    "DT_CLIMATE_G1_CMIP6_HIST_IFS_FESOM_R1": ["dedt_lumi"],
    "DT_CLIMATE_G1_SCENARIOMIP_SSP3_7_0_IFS_FESOM_R2": ["dedt_lumi"],
    "EEA_HRL_TCF": ["wekeo_main"],
    "EFAS_FORECAST": ["cop_ewds", "dedl"],
    "EFAS_HISTORICAL": ["cop_ewds", "dedl"],
    "EFAS_REFORECAST": ["cop_ewds", "dedl"],
    "EFAS_SEASONAL": ["cop_ewds", "dedl"],
    "EFAS_SEASONAL_REFORECAST": ["cop_ewds", "dedl"],
    "ERA5_LAND": ["cop_cds", "dedl", "wekeo_ecmwf"],
    "ERA5_LAND_MONTHLY": ["cop_cds", "dedl", "wekeo_ecmwf"],
    "ERA5_PL": ["cop_cds", "dedl", "wekeo_ecmwf"],
    "ERA5_PL_MONTHLY": ["cop_cds", "dedl", "wekeo_ecmwf"],
    "ERA5_SL": ["cop_cds", "dedl", "wekeo_ecmwf"],
    "ERA5_SL_MONTHLY": ["cop_cds", "dedl", "wekeo_ecmwf"],
    "EUSTAT_AVAILABLE_BEDS_HOSPITALS_NUTS2": ["dedl"],
    "EUSTAT_BATHING_SITES_WATER_QUALITY": ["dedl"],
    "EUSTAT_GREENHOUSE_GAS_EMISSION_AGRICULTURE": ["dedl"],
    "EUSTAT_POP_AGE_GROUP_SEX_NUTS3": ["dedl"],
    "EUSTAT_POP_AGE_SEX_NUTS2": ["dedl"],
    "EUSTAT_POP_CHANGE_DEMO_BALANCE_CRUDE_RATES_NUTS3": ["dedl"],
    "EUSTAT_POP_DENSITY_NUTS3": ["dedl"],
    "EUSTAT_SHARE_ENERGY_FROM_RENEWABLE": ["dedl"],
    "EUSTAT_SOIL_SEALING_INDEX": ["dedl"],
    "EUSTAT_SURFACE_TERRESTRIAL_PROTECTED_AREAS": ["dedl"],
    "FIRE_HISTORICAL": ["cop_ewds", "dedl", "wekeo_ecmwf"],
    "FIRE_SEASONAL": ["cop_ewds"],
    "GHS_BUILT_C": ["cop_ghsl"],
    "GHS_BUILT_H": ["cop_ghsl"],
    "GHS_BUILT_LAUSTAT": ["cop_ghsl"],
    "GHS_BUILT_S": ["cop_ghsl"],
    "GHS_BUILT_V": ["cop_ghsl"],
    "GHS_DUC": ["cop_ghsl"],
    "GHS_ENACT_POP": ["cop_ghsl"],
    "GHS_ESM": ["cop_ghsl"],
    "GHS_FUA": ["cop_ghsl"],
    "GHS_LAND": ["cop_ghsl"],
    "GHS_POP": ["cop_ghsl"],
    "GHS_SMOD": ["cop_ghsl"],
    "GHS_UCDB_DOMAIN": ["cop_ghsl"],
    "GHS_UCDB_REGION": ["cop_ghsl"],
    "GLACIERS_DIST_RANDOLPH": ["cop_cds", "dedl", "wekeo_ecmwf"],
    "GLOFAS_FORECAST": ["cop_ewds", "dedl"],
    "GLOFAS_HISTORICAL": ["cop_ewds", "dedl"],
    "GLOFAS_REFORECAST": ["cop_ewds", "dedl"],
    "GLOFAS_SEASONAL": ["cop_ewds", "dedl"],
    "GLOFAS_SEASONAL_REFORECAST": ["cop_ewds", "dedl"],
    "GRIDDED_GLACIERS_MASS_CHANGE": ["cop_cds", "dedl", "wekeo_ecmwf"],
    "GSW_CHANGE": ["dedl"],
    "GSW_EXTENT": ["dedl"],
    "GSW_OCCURRENCE": ["dedl"],
    "GSW_RECURRENCE": ["dedl"],
    "GSW_SEASONALITY": ["dedl"],
    "GSW_TRANSITIONS": ["dedl"],
    "ISIMIP_CLIMATE_FORCING_ISIMIP3B": ["dedl"],
    "ISIMIP_SOCIO_ECONOMIC_FORCING_ISIMIP3B": ["dedl"],
    "L8_OLI_TIRS_C1L1": ["aws_eos", "earth_search_gcs"],
    "LANDSAT_C2L1": [
        "dedl",
        "planetary_computer",
        "usgs",
        "usgs_satapi_aws",
    ],
    "LANDSAT_C2L2": ["dedl", "earth_search", "planetary_computer", "usgs"],
    "LANDSAT_C2L2ALB_BT": ["usgs_satapi_aws"],
    "LANDSAT_C2L2ALB_SR": ["usgs_satapi_aws"],
    "LANDSAT_C2L2ALB_ST": ["usgs_satapi_aws"],
    "LANDSAT_C2L2ALB_TA": ["usgs_satapi_aws"],
    "LANDSAT_C2L2_SR": ["usgs_satapi_aws"],
    "LANDSAT_C2L2_ST": ["usgs_satapi_aws"],
    "LANDSAT_ETM_C1": ["usgs"],
    "LANDSAT_ETM_C2L1": ["usgs"],
    "LANDSAT_ETM_C2L2": ["usgs"],
    "LANDSAT_TM_C1": ["usgs"],
    "LANDSAT_TM_C2L1": ["usgs"],
    "LANDSAT_TM_C2L2": ["usgs"],
    "METOP_AMSU_L1": ["dedl", "eumetsat_ds"],
    "METOP_ASCSZF1B": ["dedl", "eumetsat_ds"],
    "METOP_ASCSZFR02": ["dedl", "eumetsat_ds"],
    "METOP_ASCSZO1B": ["dedl", "eumetsat_ds"],
    "METOP_ASCSZOR02": ["dedl", "eumetsat_ds"],
    "METOP_ASCSZR1B": ["dedl", "eumetsat_ds"],
    "METOP_ASCSZRR02": ["dedl", "eumetsat_ds"],
    "METOP_AVHRRL1": ["dedl", "eumetsat_ds"],
    "METOP_AVHRRGACR02": ["dedl", "eumetsat_ds"],
    "METOP_GLB_SST_NC": ["dedl", "eumetsat_ds"],
    "METOP_GOMEL1": ["dedl", "eumetsat_ds"],
    "METOP_GOMEL1R03": ["dedl", "eumetsat_ds"],
    "METOP_HIRSL1": ["dedl", "eumetsat_ds"],
    "METOP_IASTHR011": ["dedl", "eumetsat_ds"],
    "METOP_IASSND02": ["dedl", "eumetsat_ds"],
    "METOP_IASIL1C_ALL": ["dedl", "eumetsat_ds"],
    "METOP_LSA_002": ["dedl", "eumetsat_ds"],
    "METOP_MHSL1": ["dedl", "eumetsat_ds"],
    "METOP_OSI_104": ["dedl", "eumetsat_ds"],
    "METOP_OSI_150A": ["dedl", "eumetsat_ds"],
    "METOP_OSI_150B": ["dedl", "eumetsat_ds"],
    "METOP_SOMO12": ["dedl", "eumetsat_ds"],
    "METOP_SOMO25": ["dedl", "eumetsat_ds"],
    "MSG_CLM": ["dedl", "eumetsat_ds"],
    "MSG_CLM_IODC": ["dedl", "eumetsat_ds"],
    "MSG_GSAL2R02": ["dedl", "eumetsat_ds"],
    "MSG_HRSEVIRI": ["dedl", "eumetsat_ds"],
    "MSG_HRSEVIRI_IODC": ["dedl", "eumetsat_ds"],
    "MSG_RSS_CLM": ["dedl", "eumetsat_ds"],
    "MSG_MSG15_RSS": ["dedl", "eumetsat_ds"],
    "MSG_LSA_FRM": ["dedl", "eumetsat_ds"],
    "MSG_LSA_LST_CDR": ["dedl", "eumetsat_ds"],
    "MSG_LSA_LSTDE": ["dedl", "eumetsat_ds"],
    "MSG_AMVR02": ["dedl", "eumetsat_ds"],
    "MSG_CTH": ["eumetsat_ds"],
    "MSG_CTH_IODC": ["eumetsat_ds"],
    "MFG_GSA_57": ["eumetsat_ds"],
    "MFG_GSA_63": ["eumetsat_ds"],
    "MSG_MFG_GSA_0": ["eumetsat_ds"],
    "HIRS_FDR_1_MULTI": ["eumetsat_ds"],
    "MSG_OCA_CDR": ["eumetsat_ds"],
    "S6_RADIO_OCCULTATION": ["eumetsat_ds"],
    "MTG_LI_AF": ["eumetsat_ds"],
    "MTG_LI_LFL": ["eumetsat_ds"],
    "MTG_LI_LGR": ["eumetsat_ds"],
    "MTG_LI_AFA": ["eumetsat_ds"],
    "MTG_LI_AFR": ["eumetsat_ds"],
    "MTG_LI_LEF": ["eumetsat_ds"],
    "MTG_FCI_FDHSI": ["eumetsat_ds"],
    "MTG_FCI_HRFI": ["eumetsat_ds"],
    "MTG_FCI_ASR_BUFR": ["eumetsat_ds"],
    "MTG_FCI_ASR_NETCDF": ["eumetsat_ds"],
    "MTG_FCI_AMV_BUFR": ["eumetsat_ds"],
    "MTG_FCI_AMV_NETCDF": ["eumetsat_ds"],
    "MTG_FCI_CLM": ["eumetsat_ds"],
    "MTG_FCI_GII": ["eumetsat_ds"],
    "MTG_FCI_OCA": ["eumetsat_ds"],
    "MTG_FCI_OLR": ["eumetsat_ds"],
    "MSG_SEVIRI_RSS_AMV_CDR_V1": ["eumetsat_ds"],
    "MSG_SEVIRI_RSS_HR_IMG_L1_5_V1": ["eumetsat_ds"],
    "MSG_SEVIRI_SARAH_CDR_V003": ["eumetsat_ds"],
    "MTG_FCI_ACTIVE_FIRE_L2_V1": ["eumetsat_ds"],
    "MULT_PMW_IR_GIRAFE_PRECIP_CDR_V001": ["eumetsat_ds"],
    "MODIS_MCD43A4": ["aws_eos", "planetary_computer"],
    "MO_GLOBAL_ANALYSISFORECAST_PHY_001_024": ["cop_marine", "dedl"],
    "MO_GLOBAL_ANALYSISFORECAST_BGC_001_028": ["cop_marine", "dedl"],
    "MO_GLOBAL_ANALYSISFORECAST_WAV_001_027": ["cop_marine", "dedl"],
    "MO_GLOBAL_MULTIYEAR_BGC_001_033": ["cop_marine", "dedl"],
    "MO_GLOBAL_MULTIYEAR_WAV_001_032": ["cop_marine", "dedl"],
    "MO_GLOBAL_MULTIYEAR_PHY_ENS_001_031": ["cop_marine", "dedl"],
    "MO_INSITU_GLO_PHY_UV_DISCRETE_NRT_013_048": ["cop_marine", "dedl"],
    "MO_INSITU_GLO_PHY_TS_OA_NRT_013_002": ["cop_marine", "dedl"],
    "MO_INSITU_GLO_PHY_TS_OA_MY_013_052": ["cop_marine", "dedl"],
    "MO_MULTIOBS_GLO_BIO_BGC_3D_REP_015_010": ["cop_marine", "dedl"],
    "MO_MULTIOBS_GLO_BIO_CARBON_SURFACE_MYNRT_015_008": ["cop_marine", "dedl"],
    "MO_MULTIOBS_GLO_BGC_NUTRIENTS_CARBON_PROFILES_MYNRT_015_009": [
        "cop_marine",
        "dedl",
    ],
    "MO_MULTIOBS_GLO_PHY_MYNRT_015_003": ["cop_marine", "dedl"],
    "MO_MULTIOBS_GLO_PHY_S_SURFACE_MYNRT_015_013": ["cop_marine", "dedl"],
    "MO_MULTIOBS_GLO_PHY_TSUV_3D_MYNRT_015_012": ["cop_marine", "dedl"],
    "MO_MULTIOBS_GLO_PHY_W_3D_REP_015_007": ["cop_marine", "dedl"],
    "MO_SEAICE_GLO_SEAICE_L4_NRT_OBSERVATIONS_011_001": ["cop_marine", "dedl"],
    "MO_SEAICE_GLO_SEAICE_L4_REP_OBSERVATIONS_011_009": ["cop_marine", "dedl"],
    "MO_SEAICE_GLO_SEAICE_L4_NRT_OBSERVATIONS_011_006": ["cop_marine", "dedl"],
    "MO_SEALEVEL_GLO_PHY_L4_NRT_008_046": ["cop_marine", "dedl"],
    "MO_SEALEVEL_GLO_PHY_MDT_008_063": ["cop_marine", "dedl"],
    "MO_SST_GLO_SST_L3S_NRT_OBSERVATIONS_010_010": ["cop_marine", "dedl"],
    "MO_SST_GLO_SST_L4_NRT_OBSERVATIONS_010_001": ["cop_marine", "dedl"],
    "MO_SST_GLO_SST_L4_REP_OBSERVATIONS_010_011": ["cop_marine", "dedl"],
    "MO_SST_GLO_SST_L4_REP_OBSERVATIONS_010_024": ["cop_marine", "dedl"],
    "MO_WAVE_GLO_PHY_SPC_FWK_L3_NRT_014_002": ["cop_marine", "dedl"],
    "MO_WAVE_GLO_PHY_SWH_L3_NRT_014_001": ["cop_marine", "dedl"],
    "MO_WAVE_GLO_PHY_SWH_L4_NRT_014_003": ["cop_marine", "dedl"],
    "MO_WIND_GLO_PHY_CLIMATE_L4_MY_012_003": ["cop_marine", "dedl"],
    "MO_WIND_GLO_PHY_L3_NRT_012_002": ["cop_marine", "dedl"],
    "MO_WIND_GLO_PHY_L3_MY_012_005": ["cop_marine", "dedl"],
    "MO_WIND_GLO_PHY_L4_NRT_012_004": ["cop_marine", "dedl"],
    "MO_WIND_GLO_PHY_L4_MY_012_006": ["cop_marine", "dedl"],
    "MO_OCEANCOLOUR_GLO_BGC_L3_MY_009_107": ["cop_marine", "dedl"],
    "MO_OCEANCOLOUR_GLO_BGC_L3_NRT_009_101": ["cop_marine", "dedl"],
    "MO_OCEANCOLOUR_GLO_BGC_L3_MY_009_103": ["cop_marine", "dedl"],
    "MO_OCEANCOLOUR_GLO_BGC_L4_NRT_009_102": ["cop_marine", "dedl"],
    "MO_OCEANCOLOUR_GLO_BGC_L4_MY_009_104": ["cop_marine", "dedl"],
    "MO_OCEANCOLOUR_GLO_BGC_L4_MY_009_108": ["cop_marine", "dedl"],
    "NAIP": ["aws_eos", "earth_search", "planetary_computer"],
    "NEMSAUTO_TCDC": ["meteoblue"],
    "NEMSGLOBAL_TCDC": ["meteoblue"],
    "S1_AUX_GNSSRD": [
        "cop_dataspace",
        "cop_dataspace_s3",
        "creodias",
        "creodias_s3",
    ],
    "S1_AUX_MOEORB": [
        "cop_dataspace",
        "cop_dataspace_s3",
        "creodias",
        "creodias_s3",
    ],
    "S1_AUX_POEORB": [
        "cop_dataspace",
        "cop_dataspace_s3",
        "creodias",
        "creodias_s3",
    ],
    "S1_AUX_PREORB": [
        "cop_dataspace",
        "cop_dataspace_s3",
        "creodias",
        "creodias_s3",
    ],
    "S1_AUX_PROQUA": [
        "cop_dataspace",
        "cop_dataspace_s3",
        "creodias",
        "creodias_s3",
    ],
    "S1_AUX_RESORB": [
        "cop_dataspace",
        "cop_dataspace_s3",
        "creodias",
        "creodias_s3",
    ],
    "S1_SAR_GRD": [
        "aws_eos",
        "cop_dataspace",
        "cop_dataspace_s3",
        "creodias",
        "creodias_s3",
        "dedl",
        "earth_search",
        "geodes",
        "geodes_s3",
        "planetary_computer",
        "sara",
        "wekeo_main",
    ],
    "S1_SAR_GRD_COG": ["cop_dataspace", "cop_dataspace_s3"],
    "S1_SAR_L3_IW_MCM": [
        "creodias",
        "cop_dataspace",
        "creodias_s3",
        "cop_dataspace_s3",
    ],
    "S1_SAR_L3_DH_MCM": [
        "creodias",
        "cop_dataspace",
        "creodias_s3",
        "cop_dataspace_s3",
    ],
    "S1_SAR_OCN": [
        "cop_dataspace",
        "cop_dataspace_s3",
        "creodias",
        "creodias_s3",
        "geodes",
        "geodes_s3",
        "sara",
        "wekeo_main",
    ],
    "S1_SAR_RAW": [
        "cop_dataspace",
        "cop_dataspace_s3",
        "creodias",
        "creodias_s3",
        "wekeo_main",
    ],
    "S1_SAR_SLC": [
        "cop_dataspace",
        "cop_dataspace_s3",
        "creodias",
        "creodias_s3",
        "dedl",
        "geodes",
        "geodes_s3",
        "sara",
        "wekeo_main",
    ],
    "S2_MSI_L1C": [
        "aws_eos",
        "cop_dataspace",
        "cop_dataspace_s3",
        "creodias",
        "creodias_s3",
        "dedl",
        "earth_search",
        "earth_search_gcs",
        "geodes",
        "geodes_s3",
        "sara",
        "usgs",
        "wekeo_main",
    ],
    "S2_MSI_L2A": [
        "aws_eos",
        "cop_dataspace",
        "cop_dataspace_s3",
        "creodias",
        "creodias_s3",
        "dedl",
        "planetary_computer",
        "sara",
        "wekeo_main",
    ],
    "S2_MSI_L2A_COG": ["earth_search"],
    "S2_MSI_L2A_MAJA": ["geodes", "geodes_s3"],
    "S2_MSI_L2B_MAJA_SNOW": ["geodes", "geodes_s3"],
    "S2_MSI_L2B_MAJA_WATER": ["geodes", "geodes_s3"],
    "S3_EFR": [
        "cop_dataspace",
        "cop_dataspace_s3",
        "creodias",
        "creodias_s3",
        "dedl",
        "eumetsat_ds",
        "sara",
        "wekeo_main",
    ],
    "S3_EFR_BC002": ["eumetsat_ds"],
    "S3_ERR": [
        "cop_dataspace",
        "cop_dataspace_s3",
        "creodias",
        "creodias_s3",
        "dedl",
        "eumetsat_ds",
        "sara",
        "wekeo_main",
    ],
    "S3_ERR_BC002": ["eumetsat_ds"],
    "S3_LAN": [
        "cop_dataspace",
        "cop_dataspace_s3",
        "creodias",
        "creodias_s3",
        "dedl",
        "sara",
        "wekeo_main",
    ],
    "S3_OLCI_L2LFR": [
        "cop_dataspace",
        "cop_dataspace_s3",
        "creodias",
        "creodias_s3",
        "dedl",
        "sara",
        "wekeo_main",
    ],
    "S3_OLCI_L2LRR": [
        "cop_dataspace",
        "cop_dataspace_s3",
        "creodias",
        "creodias_s3",
        "dedl",
        "sara",
        "wekeo_main",
    ],
    "S3_OLCI_L2WFR": [
        "cop_dataspace",
        "cop_dataspace_s3",
        "creodias",
        "creodias_s3",
        "dedl",
        "eumetsat_ds",
        "sara",
        "wekeo_main",
    ],
    "S3_OLCI_L2WRR": [
        "cop_dataspace",
        "cop_dataspace_s3",
        "creodias",
        "creodias_s3",
        "dedl",
        "eumetsat_ds",
        "sara",
        "wekeo_main",
    ],
    "S3_RAC": ["sara"],
    "S3_SLSTR_L1RBT": [
        "cop_dataspace",
        "cop_dataspace_s3",
        "creodias",
        "creodias_s3",
        "dedl",
        "eumetsat_ds",
        "sara",
        "wekeo_main",
    ],
    "S3_SLSTR_L1RBT_BC003": ["eumetsat_ds"],
    "S3_SLSTR_L2": ["wekeo_main"],
    "S3_SLSTR_L2AOD": [
        "cop_dataspace",
        "cop_dataspace_s3",
        "creodias",
        "creodias_s3",
        "dedl",
        "eumetsat_ds",
        "sara",
    ],
    "S3_SLSTR_L2FRP": [
        "cop_dataspace",
        "cop_dataspace_s3",
        "creodias",
        "creodias_s3",
        "dedl",
        "eumetsat_ds",
        "sara",
    ],
    "S3_SLSTR_L2LST": [
        "cop_dataspace",
        "cop_dataspace_s3",
        "creodias",
        "creodias_s3",
        "dedl",
        "sara",
    ],
    "S3_SLSTR_L2WST": [
        "cop_dataspace",
        "cop_dataspace_s3",
        "creodias",
        "creodias_s3",
        "dedl",
        "eumetsat_ds",
        "sara",
    ],
    "S3_SRA": [
        "cop_dataspace",
        "cop_dataspace_s3",
        "creodias",
        "creodias_s3",
        "dedl",
        "eumetsat_ds",
        "sara",
        "wekeo_main",
    ],
    "S3_SRA_A": [
        "cop_dataspace",
        "cop_dataspace_s3",
        "creodias",
        "creodias_s3",
        "dedl",
        "eumetsat_ds",
        "sara",
        "wekeo_main",
    ],
    "S3_SRA_BS": [
        "cop_dataspace",
        "cop_dataspace_s3",
        "creodias",
        "creodias_s3",
        "dedl",
        "eumetsat_ds",
        "sara",
        "wekeo_main",
    ],
    "S3_SY_AOD": [
        "cop_dataspace",
        "cop_dataspace_s3",
        "creodias",
        "creodias_s3",
        "sara",
    ],
    "S3_SY_SYN": [
        "cop_dataspace",
        "cop_dataspace_s3",
        "creodias",
        "creodias_s3",
        "sara",
    ],
    "S3_SY_V10": [
        "cop_dataspace",
        "cop_dataspace_s3",
        "creodias",
        "creodias_s3",
        "sara",
    ],
    "S3_SY_VG1": [
        "cop_dataspace",
        "cop_dataspace_s3",
        "creodias",
        "creodias_s3",
        "sara",
    ],
    "S3_SY_VGP": [
        "cop_dataspace",
        "cop_dataspace_s3",
        "creodias",
        "creodias_s3",
        "sara",
    ],
    "S3_WAT": [
        "cop_dataspace",
        "cop_dataspace_s3",
        "creodias",
        "creodias_s3",
        "dedl",
        "eumetsat_ds",
        "sara",
        "wekeo_main",
    ],
    "S3_LAN_HY": [
        "wekeo_main",
        "cop_dataspace",
        "cop_dataspace_s3",
        "creodias",
        "creodias_s3",
    ],
    "S3_LAN_SI": [
        "wekeo_main",
        "cop_dataspace",
        "cop_dataspace_s3",
        "creodias",
        "creodias_s3",
    ],
    "S3_LAN_LI": [
        "wekeo_main",
        "cop_dataspace",
        "cop_dataspace_s3",
        "creodias",
        "creodias_s3",
    ],
    "S5P_L1B_IR_ALL": ["dedl", "wekeo_main"],
    "S5P_L2_IR_ALL": ["dedl", "wekeo_main"],
    "S3_OLCI_L2WFR_BC003": ["eumetsat_ds"],
    "S3_OL_2_WFRBC003": ["eumetsat_ds"],
    "S3_OLCI_L2WRR_BC003": ["eumetsat_ds"],
    "S3_SRA_1A_BC004": ["eumetsat_ds"],
    "S3_SRA_1A_BC005": ["eumetsat_ds"],
    "S3_SRA_1B_BC004": ["eumetsat_ds"],
    "S3_SRA_1B_BC005": ["eumetsat_ds"],
    "S3_SRA_BS_BC004": ["eumetsat_ds"],
    "S3_SRA_BS_BC005": ["eumetsat_ds"],
    "S3_WAT_BC004": ["eumetsat_ds"],
    "S3_WAT_BC005": ["eumetsat_ds"],
    "S3_SLSTR_L1RBT_BC004": ["eumetsat_ds"],
    "S3_SLSTR_L2WST_BC003": ["eumetsat_ds"],
    "S5P_L1B_IR_SIR": [
        "cop_dataspace",
        "cop_dataspace_s3",
        "creodias",
        "creodias_s3",
    ],
    "S5P_L1B_IR_UVN": [
        "cop_dataspace",
        "cop_dataspace_s3",
        "creodias",
        "creodias_s3",
    ],
    "S5P_L1B_RA_BD1": [
        "cop_dataspace",
        "cop_dataspace_s3",
        "creodias",
        "creodias_s3",
    ],
    "S5P_L1B_RA_BD2": [
        "cop_dataspace",
        "cop_dataspace_s3",
        "creodias",
        "creodias_s3",
    ],
    "S5P_L1B_RA_BD3": [
        "cop_dataspace",
        "cop_dataspace_s3",
        "creodias",
        "creodias_s3",
    ],
    "S5P_L1B_RA_BD4": [
        "cop_dataspace",
        "cop_dataspace_s3",
        "creodias",
        "creodias_s3",
    ],
    "S5P_L1B_RA_BD5": [
        "cop_dataspace",
        "cop_dataspace_s3",
        "creodias",
        "creodias_s3",
    ],
    "S5P_L1B_RA_BD6": [
        "cop_dataspace",
        "cop_dataspace_s3",
        "creodias",
        "creodias_s3",
    ],
    "S5P_L1B_RA_BD7": [
        "cop_dataspace",
        "cop_dataspace_s3",
        "creodias",
        "creodias_s3",
    ],
    "S5P_L1B_RA_BD8": [
        "cop_dataspace",
        "cop_dataspace_s3",
        "creodias",
        "creodias_s3",
    ],
    "S5P_L2_AER_AI": [
        "cop_dataspace",
        "cop_dataspace_s3",
        "creodias",
        "creodias_s3",
    ],
    "S5P_L2_AER_LH": [
        "cop_dataspace",
        "cop_dataspace_s3",
        "creodias",
        "creodias_s3",
    ],
    "S5P_L2_CH4": ["cop_dataspace", "cop_dataspace_s3", "creodias", "creodias_s3"],
    "S5P_L2_CLOUD": [
        "cop_dataspace",
        "cop_dataspace_s3",
        "creodias",
        "creodias_s3",
    ],
    "S5P_L2_CO": ["cop_dataspace", "cop_dataspace_s3", "creodias", "creodias_s3"],
    "S5P_L2_HCHO": ["cop_dataspace", "cop_dataspace_s3", "creodias", "creodias_s3"],
    "S5P_L2_NO2": ["cop_dataspace", "cop_dataspace_s3", "creodias", "creodias_s3"],
    "S5P_L2_NP_BD3": [
        "cop_dataspace",
        "cop_dataspace_s3",
        "creodias",
        "creodias_s3",
    ],
    "S5P_L2_NP_BD6": [
        "cop_dataspace",
        "cop_dataspace_s3",
        "creodias",
        "creodias_s3",
    ],
    "S5P_L2_NP_BD7": [
        "cop_dataspace",
        "cop_dataspace_s3",
        "creodias",
        "creodias_s3",
    ],
    "S5P_L2_O3": ["cop_dataspace", "cop_dataspace_s3", "creodias", "creodias_s3"],
    "S5P_L2_O3_PR": [
        "cop_dataspace",
        "cop_dataspace_s3",
        "creodias",
        "creodias_s3",
    ],
    "S5P_L2_O3_TCL": [
        "cop_dataspace",
        "cop_dataspace_s3",
        "creodias",
        "creodias_s3",
    ],
    "S5P_L2_SO2": ["cop_dataspace", "cop_dataspace_s3", "creodias", "creodias_s3"],
    "SATELLITE_CARBON_DIOXIDE": ["cop_cds", "dedl", "wekeo_ecmwf"],
    "SATELLITE_FIRE_BURNED_AREA": ["cop_cds", "wekeo_ecmwf"],
    "SATELLITE_METHANE": ["cop_cds", "dedl", "wekeo_ecmwf"],
    "SATELLITE_SEA_ICE_EDGE_TYPE": ["cop_cds", "dedl", "wekeo_ecmwf"],
    "SATELLITE_SEA_LEVEL_GLOBAL": ["cop_cds", "dedl", "wekeo_ecmwf"],
    "SATELLITE_SEA_ICE_CONCENTRATION": ["cop_cds", "dedl", "wekeo_ecmwf"],
    "SATELLITE_SEA_ICE_THICKNESS": ["cop_cds", "dedl", "wekeo_ecmwf"],
    "SEASONAL_MONTHLY_PL": ["cop_cds", "dedl", "wekeo_ecmwf"],
    "SEASONAL_MONTHLY_SL": ["cop_cds", "dedl", "wekeo_ecmwf"],
    "SEASONAL_ORIGINAL_PL": ["cop_cds", "dedl", "wekeo_ecmwf"],
    "SEASONAL_ORIGINAL_SL": ["cop_cds", "dedl", "wekeo_ecmwf"],
    "SEASONAL_POSTPROCESSED_PL": ["cop_cds", "dedl", "wekeo_ecmwf"],
    "SEASONAL_POSTPROCESSED_SL": ["cop_cds", "dedl", "wekeo_ecmwf"],
    "SIS_HYDRO_MET_PROJ": ["cop_cds", "dedl"],
    "CMIP6_CLIMATE_PROJECTIONS": ["cop_cds"],
    "TIGGE_CF_SFC": ["ecmwf"],
    "UERRA_EUROPE_SL": ["cop_cds", "dedl", "wekeo_ecmwf"],
    "SPACENET_BUILDINGS_DETECTION_V1": ["dedl"],
    "SPACENET_ALL_WEATHER_MAPPING": ["dedl"],
    "SPACENET_BUILDINGS_DETECTION_V2": ["dedl"],
    "SPACENET_ROADS_NETWORK_DETECTION": ["dedl"],
    "SPACENET_OFF_NADIR_BUILDING": ["dedl"],
    "SPACENET_ROADS_NETWORK_ROUTE_TRAVEL": ["dedl"],
    GENERIC_COLLECTION: [
        "usgs",
        "creodias",
        "usgs_satapi_aws",
        "earth_search",
        "earth_search_gcs",
        "ecmwf",
        "cop_ads",
        "cop_cds",
        "meteoblue",
        "cop_dataspace",
        "planetary_computer",
        "hydroweb_next",
        "creodias_s3",
        "dedl",
    ],
}
SUPPORTED_PROVIDERS = [
    "aws_eos",
    "cop_ads",
    "cop_cds",
    "cop_dataspace",
    "cop_dataspace_s3",
    "cop_ewds",
    "cop_ghsl",
    "cop_marine",
    "creodias",
    "creodias_s3",
    "dedl",
    "dedt_lumi",
    "dedt_mn5",
    "earth_search",
    "earth_search_gcs",
    "ecmwf",
    "eocat",
    "eumetsat_ds",
    "fedeo_ceda",
    "geodes",
    "geodes_s3",
    "hydroweb_next",
    "meteoblue",
    "planetary_computer",
    "sara",
    "usgs",
    "usgs_satapi_aws",
    "wekeo_cmems",
    "wekeo_ecmwf",
    "wekeo_main",
]

__all__ = ["SUPPORTED_COLLECTIONS", "SUPPORTED_PROVIDERS"]
